version: '3.1'
volumes:
  db-data:
services:
  mysql:
    container_name: gu-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: guadmin
      MYSQL_PASSWORD: gupass
      MYSQL_DATABASE: location
      TZ: Etc/GMT-2
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

