basePath: /v1
definitions:
  locations.MessageResponse:
    properties:
      message:
        type: string
    type: object
  locations.NewLocationRequest:
    properties:
      coordinates:
        example: 39.12355, 27.64538
        type: string
      uid:
        example: 800
        type: integer
      username:
        example: Bill
        type: string
    required:
    - coordinates
    type: object
host: localhost:8080
info:
  contact:
    email: kvendingoldo@gmail.com
    name: Alexander Sharov
    url: http://github.com/kvendingoldo
  description: Documentation's GU location service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GU location service
  version: "1.0"
paths:
  /distance:
    get:
      description: Returns distance traveled by a person within some date/time range
        (in days).
      parameters:
      - description: id of user
        in: query
        name: uid
        required: true
        type: integer
      - description: time range
        in: query
        name: range
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: integer
      summary: Returns distance traveled by a person within some date/time range (in
        days).
      tags:
      - location
  /location:
    put:
      description: Update current user location by the username/uid.
      parameters:
      - description: body data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/locations.NewLocationRequest'
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Update current user location by the username/uid.
      tags:
      - location
  /search:
    get:
      description: Search for users in some location within the provided radius (with
        pagination).
      parameters:
      - description: 'search center '
        in: query
        name: coordinate
        required: true
        type: string
      - description: radius (in meters)
        in: query
        name: radius
        type: number
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/locations.MessageResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/locations.MessageResponse'
      summary: Search in some location within the provided radius.
      tags:
      - location
swagger: "2.0"
